### PR TITLE
Adds newline after each concatted file

### PR DESCRIPTION
**Pull request by madeofpeople**
adds options.insertNewLine [true]
includes test coverage

### CODE REVIEW

**Comment by aymericbeaumet** [comment]
Thanks

**Comment by madeofpeople** [comment]
Thank you for the useful thing.

**Comment by aymericbeaumet** [comment]
Forgot to tell you to update the readme. Could you do it?


—
Aymeric BeaumetBackend Engineer

**Comment by aymericbeaumet** [comment]
Nevermind, I'll do it while updating the changelog.

**Comment by madeofpeople** [comment]
:+1:

**Pull request merged**
